### ISSUE TITLE
WHOIS process cannot create .pid file

### ISSUE THREAD

**Issue by artur-beljajev** [internetee/whois#12]
Create empty file `.gitkeep` at `tmp/pids`

https://gist.github.com/artur-beljajev/88633b8aae42ab54528a950daff91de7

**Comment by teadur** [comment]
whois i ran from init script what creates the pidfile

**Comment by artur-beljajev** [comment]
I followed "Demo Installation" section instead. I guess it should work out-of-the-box in this case as well.

**Comment by teadur** [comment]
im not sure whats the goal of demo installation, maybe we should remove to cleanup the documentation ?

**Comment by artur-beljajev** [comment]
I think it is better to leave some option to be able to use it without any init scripts and Mina. For example, it is useful for development. Perhaps there is some another way to do proper development?

**Comment by teadur** [comment]
fixed in #18
