### ISSUE TITLE
GDPR: hide data of private registrants

### ISSUE THREAD

**Issue by vohmar** [internetee/whois#24]
In relation to upcoming GDPR requirements there need to be some chagnes in data returned for private registrants and their representatives.

WHOIS API must verify the type of registrant of requested domain. If registrant ident type is priv or birthday then in the output replace
* name = Private person
* id = Not Disclosed
* country = Not Disclosed
* admin contact name = Not Disclosed
* tech contact name = Not Disclosed

Email value of "Not Disclosed - Visit www.internet.ee for webbased WHOIS" must be kept for all contacts as is

Add disclaimer before the output data from the database - depends on ticket https://github.com/internetee/registry/issues/795

**Comment by maciej-szlosarczyk** [comment]
Hey @vohmar, I have some questions here. Basically all of those GDPR/whois generation tasks are very related and it would be best if we do them in one go. Here's a compilation of info that I gathered from different places in a form of a table (post-GDPR). Changes are in **bold**. Please confirm that the list is complete:

## Private Person
### UNIX WHOIS
| Field | Pre-GDPR | Post-GDPR |
| ----- | -------- | --------- |
| name | visible | visible |
| status | visible | visible |
| changed | visible | visible |
| expire |  visible | visible |
| outzone | visible | visible |
| delete  | visible | visible |
| registrant_name | visible | **"Private person"** |
| registrant_org_id | ommited | ommited |
| registrant_country | ommited | ommited |
| email | "Not Disclosed - Visit www.internet.ee for webbased WHOIS" | "Not Disclosed - Visit www.internet.ee for webbased WHOIS |
| admin_contact_name | visible | **"Not Disclosed"** |
| admin_contact_email | "Not Disclosed - Visit www.internet.ee for webbased WHOIS" | "Not Disclosed - Visit www.internet.ee for webbased WHOIS" |
| admin_contact_changed | visible | **"Not Disclosed"** |
| technical_contact_name | visible | **"Not Disclosed"** |
| technical_contact_email | "Not Disclosed - Visit www.internet.ee for webbased WHOIS" | "Not Disclosed - Visit www.internet.ee for webbased WHOIS" |
| technical_contact_changed | visible | **"Not Disclosed"** |
| registrar_name | visible | visible |
| registrar_url | visible | visible |
| registrar_phone | visible | visible |
| registrar_changed | visible | visible |
| dns_server | visible | visible |
| dns_changed | visible | visible |
| dnssec_key | visible | visible |
| dnssec_changed | visible | visible |

### REST WHOIS
| Field | Pre-GDPR | Post-GDPR |
| ----- | -------- | --------- |
| name | visible | visible |
| status | visible | visible |
| changed | visible | visible |
| expire |  visible | visible |
| outzone | visible | visible |
| delete  | visible | visible |
| registrant_name | visible | **"Private person"** |
| registrant_org_id | ommited | ommited |
| registrant_country | ommited | ommited |
| email | Captcha | **Webform** |
| admin_contact_name | visible | **"Not Disclosed"** |
| admin_contact_email | Captcha | **Webform** |
| admin_contact_changed | visible | **"Not Disclosed"** |
| technical_contact_name | visible | **"Not Disclosed"** |
| technical_contact_email| Captcha | **Webform** |
| technical_contact_changed | visible | **"Not Disclosed"** |
| registrar_name | visible | visible |
| registrar_url | visible | visible |
| registrar_phone | visible | visible |
| registrar_changed | visible | visible |
| dns_server | visible | visible |
| dns_changed | visible | visible |
| dnssec_key | visible | visible |
| dnssec_changed | visible | visible |


## Legal person
### UNIX WHOIS
| Field | Pre-GDPR | Post-GDPR |
| ----- | -------- | --------- |
| name | visible | visible |
| status | visible | visible |
| changed | visible | visible |
| expire |  visible | visible |
| outzone | visible | visible |
| delete  | visible | visible |
| registrant_name | visible | visible |
| registrant_org_id | visible | visible |
| registrant_country | visible | visible |
| email | "Not Disclosed - Visit www.internet.ee for webbased WHOIS" | "Not Disclosed - Visit www.internet.ee for webbased WHOIS" |
| admin_contact_name | visible | **"Not Disclosed - Visit www.internet.ee for webbased WHOIS"** |
| admin_contact_email | "Not Disclosed - Visit www.internet.ee for webbased WHOIS" | "Not Disclosed - Visit www.internet.ee for webbased WHOIS" |
| admin_contact_changed | visible | **"Not Disclosed - Visit www.internet.ee for webbased WHOIS"** |
| technical_contact_name | visible | **"Not Disclosed - Visit www.internet.ee for webbased WHOIS"** |
| technical_contact_email | "Not Disclosed - Visit www.internet.ee for webbased WHOIS" | "Not Disclosed - Visit www.internet.ee for webbased WHOIS" |
| technical_contact_changed | visible | **"Not Disclosed - Visit www.internet.ee for webbased WHOIS"** |
| registrar_name | visible | visible |
| registrar_url | visible | visible |
| registrar_phone | visible | visible |
| registrar_changed | visible | visible |
| dns_server | visible | visible |
| dns_changed | visible | visible |
| dnssec_key | visible | visible |
| dnssec_changed | visible | visible |

### REST WHOIS
| Field | Pre-GDPR | Post-GDPR |
| ----- | -------- | --------- |
| name | visible | visible |
| status | visible | visible |
| changed | visible | visible |
| expire |  visible | visible |
| outzone | visible | visible |
| delete  | visible | visible |
| registrant_name | visible | visible |
| registrant_org_id | visible | visible |
| registrant_country | visible | visible |
| email | Captcha | Captcha |
| admin_contact_name | visible | **Captcha** |
| admin_contact_email | Captcha | Captcha |
| admin_contact_changed | visible | **Captcha** |
| technical_contact_name | visible | **Captcha** |
| technical_contact_email| Captcha | Captcha |
| technical_contact_changed | visible | **Captcha** |
| registrar_name | visible | visible |
| registrar_url | visible | visible |
| registrar_phone | visible | visible |
| registrar_changed | visible | visible |
| dns_server | visible | visible |
| dns_changed | visible | visible |
| dnssec_key | visible | visible |
| dnssec_changed | visible | visible |

**Comment by vohmar** [comment]
Perfect - confirmed!
