### ISSUE TITLE
GDPR: hide admin and tech contact details

### ISSUE THREAD

**Issue by vohmar** [internetee/whois#26]
In relation to upcoming GDPR requirements we have decided to hide admin and tech contact data from whois.

Currently there are all email addresses that are hidden
So in addition to that we will also hide the name of admin and technical contacts - replace it with the same text "Not Disclosed - Visit www.internet.ee for webbased WHOIS"

**Comment by maciej-szlosarczyk** [comment]
Part of this task needs to be resolved in Registry, as the UNIX body is generated there. I'll do it as part of https://github.com/internetee/registry/issues/795.
